source 'http://rubygems.org'

gem 'rails', '3.1.3'

gem 'sqlite3'

# Authentication
gem 'devise', '~> 1.4.3'

# Authorization
gem 'cancan'

# File upload
gem 'paperclip'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
	gem 'dynamic_form'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :test, :development do
  gem 'rspec-rails', '~> 2.5'
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-cucumber'
  gem 'guard-bundler'
	gem 'ruby_gntp'
	gem 'pry'
end

group :test do
  gem 'cucumber-rails', '1.0.6'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl'
  gem 'email_spec'
	gem 'launchy'
end